version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - mynetwork
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - redis
      - mysql
      - rabbitmq
    networks:
      - mynetwork
    command: npm run start

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: finalproject_db
    ports:
      - "3307:3306"
    networks:
      - mynetwork
volumes:
  app_volume:


networks:
  mynetwork:
    driver: bridge
