name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username edanurakbass --password ${{ secrets.GH_PAT}} ghcr.io
          //---app---
          docker build . --tag ghcr.io/edanurakbass/db-app-app:latest
          docker push ghcr.io/edanurakbass/db-app-app:latest
          //---redis---
          docker build . --tag ghcr.io/edanurakbass/redis:latest
          docker push ghcr.io/edanurakbass/redis:latest
          //---mysql---
          docker build . --tag ghcr.io/edanurakbass/mysql:latest
          docker push ghcr.io/edanurakbass/mysql:latest
          //---rabbitmq---
          docker build . --tag ghcr.io/edanurakbass/rabbitmq:latest
          docker push ghcr.io/edanurakbass/rabbitmq:latest
